services:
  livesync:
    image: ghcr.io/joshendriks/live-sync:main
    volumes:
      - /home/sr/data/notes/live-sync/data:/app/data
      - /home/sr/data/notes/live-sync/dat:/app/dat
      - /home/sr/data/notes/live-sync/script:/app/script
    restart: unless-stopped
    depends_on:
      - redis
  redis:
    image: redis:7.4.2
    volumes:
      - ./redis/config:/usr/local/etc/redis:rw
      - /home/sr/data/notes/redis:/data
    ports:
      - '6381:6379'
    command: redis-server /usr/local/etc/redis/redis-server.conf
    restart: unless-stopped
